/* 実ブラウザの操作・描画・エンコードを検証する。素材はテスト用の文字のみ。 */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'dev','deletion-qa');fs.mkdirSync(out,{recursive:true});
const base=process.env.DELETION_TEST_URL||'http://127.0.0.1:8770';
async function run(channel,lang){
 const browser=await chromium.launch({channel,headless:true,args:['--disable-gpu','--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('net::ERR_FAILED'))errors.push(m.text());});
 await page.route('**/*',route=>route.request().url().startsWith(base)||/^(data|blob):/.test(route.request().url())?route.continue():route.abort());
 try{
  await page.goto(base+(lang==='en'?'/en/':'/'),{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.J?.deletionUI);assert.match(await page.title(),/SYNTHIA/);
  await page.evaluate(()=>{const J=window.J;J.ensureFonts=async()=>{};J.fontCSS=(_key,size)=>`600 ${size}px Arial`;J.varFontCSS=J.fontCSS;J.metrics.clear();J.glyphs.clear();});
  const fixture=async(layout='tape',cuts=1)=>page.evaluate(({layout,cuts})=>{
   const J=window.J,p=J.defaultProject();p.seed=2;p.subtitleCues=[{id:'one',text:'AB/CD',start:0,end:2},{id:'two',text:'KEEP',start:2,end:4}];p.lyrics='AB/CD\nKEEP';p.style='mono';p.fps=10;p.res=270;p.studio.flags.characterEditing=true;p.studio.flags.export=true;p.fx={...p.fx,chroma:0,bloom:0,grain:0,scan:0,jitter:0,shake:0};p.simpleExport.duration=2;
   p.overrides[0]={cuts,layout,enter:'cut',exit:'cut',hold:'still',cam:'none',bg:'none',decor:['brackets','stripes'],treat:'none'};p.overrides[1]={...p.overrides[0]};J.uiApi.restoreProject(p);J.uiApi.seek(.65);J.ensureFonts=async()=>{};document.getElementById('studioCharacterMode').value='part';document.getElementById('studioCharacterMode').dispatchEvent(new Event('change'));document.getElementById('studio-characterEditing').open=true;document.getElementById('studioDeletionPanel').open=true;
  },{layout,cuts});
  const selectPart=async(slot,cutNumber=1)=>{
   const id=await page.evaluate(({slot,cutNumber})=>{const targets=window.J.ui.plan.effectTargets.filter(t=>t.line===0&&t.cutNumber===cutNumber);return (targets.find(t=>t.slot===slot)||(slot==='tape-row-0'?targets.find(t=>t.kind==='part'&&!t.decoration&&!t.treatment):null))?.id;},{slot,cutNumber});assert(id,slot);
   await page.locator('#studioPartTarget').selectOption(id);await page.locator('#view').focus();return id;
  };
  const state=()=>page.evaluate(()=>{const J=window.J;return {deleted:JSON.parse(JSON.stringify(J.ui.project.studio.deletedObjects)),cues:J.ui.project.subtitleCues,characters:J.ui.project.studio.characters,partTransforms:J.ui.project.studio.partTransforms};});
  const pixels=()=>page.evaluate(()=>{const J=window.J,r=new J.LayerRenderer(480,270,'alpha',0),frames=[.65,1.5,3.5].map(t=>{r.draw(J.ui.plan,t);const data=r.layer.getContext('2d').getImageData(0,0,480,270).data;let hash=2166136261,occupied=0;for(let i=0;i<data.length;i++){hash=Math.imul(hash^data[i],16777619);if(i%4===3&&data[i])occupied++;}return {hash:hash>>>0,occupied};});return frames;});
  console.log(channel,lang,'part / undo / JSON');await fixture();assert(await page.locator('#studioDeleteSelected').isDisabled());await selectPart('tape-row-0');const before=await state(),beforePlan=await page.evaluate(()=>JSON.stringify(window.J.lineSnapshot(window.J.ui.plan,1))),original=await pixels();await page.keyboard.press('Delete');const after=await state();assert.equal(Object.keys(after.deleted).length,1);assert.deepEqual(after.cues,before.cues);assert(await page.locator('#studioDeleteSelected').isDisabled());const removed=await pixels();console.log('pixel hashes',original,removed,'same other plan',beforePlan===await page.evaluate(()=>JSON.stringify(window.J.lineSnapshot(window.J.ui.plan,1))));assert.notDeepEqual(removed[0],original[0]);assert.deepEqual(removed[2],original[2]);
  await page.keyboard.press('Control+z');assert.deepEqual((await state()).deleted,{});assert.deepEqual(await pixels(),original);await page.keyboard.press('Control+y');assert.deepEqual(await pixels(),removed);
  const saved=await page.evaluate(()=>JSON.stringify(window.J.ui.project));await page.evaluate(saved=>window.J.uiApi.restoreProject(JSON.parse(saved)),saved);assert.deepEqual(await pixels(),removed);await page.evaluate(()=>{window.J.ui.project.studio.flags.characterEditing=false;window.J.uiApi.replan();});assert.deepEqual(await pixels(),removed);
  // 入力欄・ダイアログ・Tap Sync・再生・書き出し中のキーを保護する。
  console.log(channel,lang,'input guards');await fixture();await selectPart('tape-row-0');await page.locator('#lyrics').focus();await page.keyboard.press('Delete');assert.equal(Object.keys((await state()).deleted).length,0);
  await page.evaluate(()=>{const d=document.createElement('dialog');d.id='deletionTestDialog';document.body.append(d);d.showModal();});await page.keyboard.press('Backspace');assert.equal(Object.keys((await state()).deleted).length,0);await page.evaluate(()=>{document.getElementById('deletionTestDialog').close();document.getElementById('deletionTestDialog').remove();});
  for(const flag of ['tap','exporting','playing']){await page.locator('#view').focus();await page.evaluate(flag=>window.J.ui[flag]=true,flag);await page.keyboard.press('Delete');await page.evaluate(flag=>window.J.ui[flag]=false,flag);assert.equal(Object.keys((await state()).deleted).length,0);}
  // 文字クリック・Backspace・複数選択・クラスタ削除。
  console.log(channel,lang,'character / list');await fixture('center');await page.evaluate(()=>{const m=document.getElementById('studioCharacterMode');m.value='character';m.dispatchEvent(new Event('change'));window.J.uiApi.seek(.65);});await page.waitForFunction(()=>window.J.studioGlyphHits.length>0);const hit=await page.evaluate(()=>window.J.studioGlyphHits[0]),rect=await page.locator('#view').boundingBox(),size=await page.evaluate(()=>({w:document.getElementById('view').width,h:document.getElementById('view').height}));await page.locator('#view').click({position:{x:hit.x/size.w*rect.width,y:hit.y/size.h*rect.height}});await page.keyboard.press('Backspace');assert.equal(Object.values((await state()).deleted)[0].kind,'glyph');
  await fixture('center');await page.locator('#studioDeleteTargets').selectOption(['glyph-0-0','glyph-0-1']);await page.locator('#studioDeleteSelected').click();assert.equal(Object.keys((await state()).deleted).length,2);await page.locator('#view').focus();await page.keyboard.press('Control+z');assert.deepEqual((await state()).deleted,{});
  for(const kind of ['line','group']){await fixture('center');await page.locator('#studioDeleteTargets').selectOption(kind+'-0');await page.locator('#studioDeleteSelected').click();assert.equal(Object.values((await state()).deleted)[0].kind,kind);}
  await fixture();const decor=await page.evaluate(()=>window.J.ui.plan.effectTargets.find(t=>t.line===0&&t.decoration).slot);await selectPart(decor);await page.keyboard.press('Delete');assert.equal(Object.values((await state()).deleted)[0].kind,'part');
  await fixture('tape',2);await selectPart('cut',1);await page.keyboard.press('Delete');assert.equal(Object.values((await state()).deleted)[0].kind,'cut');
  await fixture('center');await page.locator('#studioDeleteTargets').selectOption('glyph-0-0');await page.locator('#studioDeleteScope').selectOption('effect');await page.locator('#studioDeleteSelected').click();assert.equal(Object.values((await state()).deleted)[0].kind,'glyph-effect');
  // 個別文字を隠しても他の文字と装飾の境界・位置は保持する。
  await fixture('center');const geometry=await page.evaluate(()=>{
   const J=window.J,p=J.ui.project,cv=document.createElement('canvas');cv.width=480;cv.height=270;const ctx=cv.getContext('2d'),renderer=new J.Renderer();
   const draw=plan=>{const cut=plan.cuts[0],env=renderer.makeEnv(ctx,plan,cut,J.STYLES[plan.style]?.schemes?.[0]||{fg:'#fff',bg:'#000',accent:'#fff'},{pass:'main',scale:1,lt:1,t:1});return J.drawItem(env,{text:cut.text,font:cut.fonts?.main||'sans',size:30,x:100,y:100});};
   const before=draw(J.plan(p));J.deleteSelectedObject(p,{kind:'glyph',line:0,index:0});return {before,after:draw(J.plan(p))};
  });assert.deepEqual(geometry.after,geometry.before);
  console.log(channel,lang,'instrumental FX');await fixture('center');await page.evaluate(()=>{const J=window.J,s=J.ui.project.studio.instrumentalFx,F=J.InstrumentalFX;s.enabled=true;s.manual=true;s.manualEffects=[F.effect({id:'manual-one',type:'Geometry Motion',start:0,end:2}),F.effect({id:'manual-two',start:0,end:2})];J.uiApi.replan();document.getElementById('studio-instrumentalFx').open=true;});await page.locator('#ifxEffect').selectOption('manual-one');await page.locator('#view').focus();await page.keyboard.press('Delete');assert.deepEqual(await page.evaluate(()=>window.J.ui.project.studio.instrumentalFx.manualEffects.map(e=>e.id)),['manual-two']);await page.keyboard.press('Control+z');assert.deepEqual(await page.evaluate(()=>window.J.ui.project.studio.instrumentalFx.manualEffects.map(e=>e.id)),['manual-one','manual-two']);await page.keyboard.press('Control+Shift+z');assert.deepEqual(await page.evaluate(()=>window.J.ui.project.studio.instrumentalFx.manualEffects.map(e=>e.id)),['manual-two']);
  // 実H.264 MP4とPNGを生成し、消去した行が画素へ戻らないことを確認する。
  await fixture('center');await page.locator('#studioDeleteTargets').selectOption('line-0');await page.locator('#studioDeleteSelected').click();
  console.log(channel,lang,'MP4 / PNG');const exported=await page.evaluate(async()=>{
   const J=window.J,p=J.ui.project,plan=J.ui.plan,range={t0:0,t1:2},pair=await J.exportLayerPair({project:p,plan,range});
   const front=await J.exportLayerFront({project:p,plan,range});const bg=J.layerCanvas(480,270),bgctx=bg.getContext('2d');bgctx.fillStyle='#245678';bgctx.fillRect(0,0,480,270);const simple=await J.exportSimpleVideo({project:p,plan,range,background:{el:bg,width:480,height:270,video:false}});const png=await J.exportStudioPNG({project:p,plan,range});
   const bytes=new Uint8Array(await png.arrayBuffer());let entry=0,offset,length;for(let i=0;i<=5;i++){const header=new DataView(bytes.buffer,entry);offset=entry+30+header.getUint16(26,true)+header.getUint16(28,true);length=header.getUint32(18,true);entry=offset+length;}const image=await createImageBitmap(new Blob([bytes.slice(offset,offset+length)],{type:'image/png'})),pngCanvas=J.layerCanvas(image.width,image.height),pngctx=pngCanvas.getContext('2d');pngctx.drawImage(image,0,0);image.close();const pngPixels=pngctx.getImageData(0,0,pngCanvas.width,pngCanvas.height).data;let pngAlphaMax=0;for(let i=3;i<pngPixels.length;i+=4)pngAlphaMax=Math.max(pngAlphaMax,pngPixels[i]);
   async function inspect(blob){const v=document.createElement('video'),url=URL.createObjectURL(blob);v.src=url;v.muted=true;await new Promise((ok,no)=>{v.onloadeddata=ok;v.onerror=()=>no(new Error('Video decode failed'));});v.currentTime=.5;await new Promise(ok=>v.onseeked=ok);const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d');x.drawImage(v,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let lo=255,hi=0;for(let i=0;i<d.length;i+=4){lo=Math.min(lo,d[i],d[i+1],d[i+2]);hi=Math.max(hi,d[i],d[i+1],d[i+2]);}v.removeAttribute('src');v.load();URL.revokeObjectURL(url);return {lo,hi};}
   const files=[...pair.files,...front.files,...simple.files],stats=[];for(const f of files)stats.push({name:f.name,size:f.blob.size,pixels:await inspect(f.blob)});
   return {stats,pngSize:png.size,pngAlphaMax,pngSampleTime:.5,pngBase64:btoa(String.fromCharCode(...bytes.slice(offset,offset+length))),manifest:pair.manifest};
  });
  fs.writeFileSync(path.join(out,channel+'-'+lang+'-first.png'),Buffer.from(exported.pngBase64,'base64'));delete exported.pngBase64;console.log('exported',exported);assert(exported.stats.every(s=>s.size>0));for(const s of exported.stats){if(s.name.includes('matte'))assert(s.pixels.lo>240,JSON.stringify(s));else if(s.name.includes('front'))assert(s.pixels.hi<16,JSON.stringify(s));else assert(s.pixels.hi-s.pixels.lo<95,JSON.stringify(s));}assert(exported.pngSize>0);assert.equal(exported.pngAlphaMax,0);
  await fixture();await selectPart('tape-row-0');await page.locator('#studioDeletionPanel').scrollIntoViewIfNeeded();await page.waitForFunction(()=>window.J.effectPartHits.length>0);await page.screenshot({path:path.join(out,channel+'-'+lang+'-selection.png'),fullPage:false});
  await page.screenshot({path:path.join(out,channel+'-'+lang+'-desktop.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,channel+'-'+lang+'-mobile.png'),fullPage:false});assert.equal(errors.length,0,errors.join('\n'));
  const result={channel,lang,url:page.url(),title:await page.title(),errors,exported};fs.writeFileSync(path.join(out,channel+'-'+lang+'.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser.close();}
}
(async()=>{
 const server=process.env.DELETION_TEST_URL?null:require('node:http').createServer((req,res)=>{
  const file={'/':'index.html','/en/':'en/index.html'}[req.url];
  if(!file){res.writeHead(404);res.end();return;}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,file)));
 });
 if(server)await new Promise(ok=>server.listen(8770,'127.0.0.1',ok));
 try{for(const channel of ['chrome','msedge'])for(const lang of ['ja','en'])await run(channel,lang);}finally{if(server)await new Promise(ok=>server.close(ok));}
})().catch(e=>{console.error(e);process.exitCode=1;});
