const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const sandbox={window:{},console,structuredClone,DOMException,setTimeout,document:{documentElement:{lang:'ja'},createElement:()=>({getContext:()=>({measureText:t=>({width:String(t).length*20})})})}};vm.createContext(sandbox);
for(const file of fs.readdirSync(path.join(__dirname,'../src')).filter(n=>n.endsWith('.js')&&n<'12').sort())vm.runInContext(fs.readFileSync(path.join(__dirname,'../src',file),'utf8'),sandbox);
const J=sandbox.window.J,F=J.InstrumentalFX,json=v=>JSON.parse(JSON.stringify(v));
const cues=[{id:'a',start:3,end:7,text:'one'},{id:'b',start:22,end:26,text:'two'}];
test('old v1 projects default OFF and preserve legacy fields on upgrade',()=>{const p=J.defaultProject();assert.equal(p.studio.instrumentalFx.enabled,false);assert.equal(p.studio.instrumentalFx.auto,false);assert.equal(p.studio.instrumentalFx.manual,false);const old={...json(p),studio:undefined,subtitleCues:cues};const q=json(old);J.upgradeLayerProject(q,old);assert.deepEqual(json(q.subtitleCues),cues);assert.equal(q.studio.instrumentalFx.enabled,false);});
test('intro, 15-second interlude and outro are union-based; boundaries remain unchanged',()=>{const before=json(cues),r=F.detect(cues,30,2,0);assert.deepEqual(json(r.map(x=>[x.start,x.end,x.type])),[[0,3,'Intro'],[7,22,'Interlude'],[26,30,'Outro']]);assert.deepEqual(cues,before);assert.deepEqual(json(F.detect([...cues,{start:5,end:23,text:'overlap'}],30,2,0).map(r=>r.type)),['Intro','Outro']);assert.equal(F.detect([{start:0,end:10,text:'one'},{start:11,end:20,text:'two'}],20,2,0).length,0);});
test('markers and fillers are non-lyric hints; no-lyric material becomes Custom',()=>{const r=F.detect([...cues,{start:7,end:22,text:'stars',filler:true},{start:8,end:21,text:'[間奏]'}],30,2,0);assert.equal(r.length,3);assert.equal(r[1].end-r[1].start,15);assert.equal(F.detect([],20)[0].type,'Custom');assert.equal(F.detect([],0).length,0);});
test('parent, auto, manual and preview gates never delete objects',()=>{const s=F.normalize({enabled:true,auto:true,manual:true,autoEffects:[{id:'a',start:0,end:3}],manualEffects:[{id:'m',start:0,end:3}]});assert.equal(F.active(s,1,'back').length,2);s.auto=false;assert.deepEqual(json(F.active(s,1,'back').map(e=>e.id)),['m']);s.auto=true;s.manual=false;assert.equal(F.active(s,1,'back')[0].id,'a');s.manual=true;s.enabled=false;assert.equal(F.active(s,1,'back').length,0);assert.equal(s.autoEffects.length+s.manualEffects.length,2);s.enabled=true;s.preview=false;assert.equal(F.active(s,1,'back',true).length,0);assert.equal(F.active(s,1,'back',false).length,2);s.auto=s.manual=false;assert.equal(F.active(s,1,'back').length,0);});
test('editing and locks apply to one independent object; JSON roundtrip retains all data',()=>{const s=F.normalize({manualEffects:[{id:'one',type:'Particle Burst'},{id:'two',type:'Geometry Motion'}]});const first=json(s.manualEffects[0]);F.updateEffect(s,'two',{x:.8,rotation:45,params:{shape:'triangle'}});assert.deepEqual(json(s.manualEffects[0]),first);F.updateEffect(s,'two',{locked:true});assert.throws(()=>F.updateEffect(s,'two',{x:.1}));F.updateEffect(s,'two',{locked:false});assert.deepEqual(json(F.normalize(json(s))),json(s));});
test('re-detection stages changed gaps and retains adjusted manual regions',()=>{const previous=F.detect(cues,30,2,0);previous[1].edited=true;previous[1].start=8;const result=F.reconcile(previous,F.detect([{start:3,end:6,text:'one'},{start:23,end:26,text:'two'}],30,2,0));assert.equal(result.conflicts.length,1);assert.equal(result.regions.find(r=>r.edited).start,8);});
test('seeded auto generation is repeatable, diverse and cannot mutate manual FX or lyrics',async()=>{const p=J.defaultProject();p.subtitleCues=cues;const s=p.studio.instrumentalFx;s.regions=F.detect(cues,30,2,0);s.manualEffects=[F.effect({id:'manual'})];const before=json(p),a={rate:1,energy:Array(30).fill(.6),onset:[],beats:Array.from({length:60},(_,i)=>i/2)};const one=await F.generate(s,s.regions,a,p,null),two=await F.generate(s,s.regions,a,p,null);assert.deepEqual(json(one),json(two));assert.deepEqual(json(p),before);assert(new Set(one.map(e=>e.type)).size>1);s.strength=0;assert.equal((await F.generate(s,s.regions,a,p,null)).length,0);});
test('no analysis still renders manual FX, silence uses deterministic fallback; beat snap is optional',()=>{const s=F.normalize({enabled:true,manual:true,manualEffects:[{id:'m'}]});assert.equal(F.pulse(s,s.manualEffects[0],1).value,0);assert.equal(F.snapTime(1.2,{beats:[1,1.5]},true),1);assert.equal(F.snapTime(1.2,{beats:[1,1.5]},false),1.2);});
test('cancelled generation never publishes partial or late results',async()=>{const ac=new AbortController();ac.abort();await assert.rejects(F.generate(F.normalize(),[{id:'r',start:0,end:20,auto:true}],null,J.defaultProject(),null,ac.signal),{name:'AbortError'});});
test('matching saved video analysis contributes Safe Zone while unavailable/mismatched results fall back',()=>{
 const p=J.defaultProject(),V=J.VideoAnalysis,result={source:{kind:'image',width:640,height:360,hash:'a'.repeat(64)},range:{start:0,end:30},options:{features:{safe:true,brightness:true},faceMargin:.15},models:{face:'test',person:'test'},scenes:[],samples:[{t:0,visionSample:true,faces:[{x:.4,y:.2,w:.2,h:.35,score:.9}],person:{grid:Array(144).fill(0)},brightness:{light:Array(48).fill(.05),complexity:Array(48).fill(0)}}]};
 const e=F.effect({id:'fx',start:7,end:22});p.videoAnalysis.regions=[{id:'protected',x:0,y:0,w:.3,h:.3,start:0,end:30,sourceHash:result.source.hash}];
 const spot=F.placement(e,{valid:true,result},p);assert(spot);assert(!(spot.x>=.4&&spot.x<=.6&&spot.y>=.2&&spot.y<=.55));assert.equal(F.placement(e,{valid:false,result},p),null);assert.equal(F.placement(e,null,p),null);
});
test('FX duration follows independent opt-in tracks; both OFF retain legacy duration and data',()=>{const p=J.defaultProject(),old=J.plan(p,null).duration,s=p.studio.instrumentalFx;s.manualEffects=[F.effect({id:'late',start:old+2,end:old+5})];assert.equal(J.plan(p,null).duration,old);s.enabled=true;assert.equal(J.plan(p,null).duration,old);s.manual=true;assert.equal(J.plan(p,null).duration,old+5);s.manual=false;s.auto=true;assert.equal(J.plan(p,null).duration,old);assert.equal(s.manualEffects.length,1);assert.equal(F.analysis({key:'x',duration:30,energy:{length:1e9}}).energy.length,0);});
test('generation snapshot identities survive repeated normalization; cross-track IDs remain independent',()=>{const s=F.normalize({autoEffects:[{id:'a'}],manualEffects:[{id:'a'}],beforeGeneration:[{id:'a'}]});assert.notEqual(s.autoEffects[0].id,s.manualEffects[0].id);assert.equal(s.beforeGeneration[0].id,'a');assert.deepEqual(json(F.normalize(json(s))),json(s));});
function recording(){const calls=[];return new Proxy({canvas:{width:640,height:360},calls,createRadialGradient:()=>({addColorStop:(...x)=>calls.push(['colorStop',...x])})},{get:(o,k)=>k in o?o[k]:(...args)=>calls.push([k,...args]),set:(o,k,v)=>{calls.push(['set',k,typeof v==='object'?'gradient':v]);o[k]=v;return true;}});}
test('all six renderers are time-addressed: seek, pause and MP4 composition share shapes',()=>{for(const type of F.types){const p=J.defaultProject();p.studio.instrumentalFx=F.normalize({enabled:true,manual:true,manualEffects:[{id:'fx',type,start:0,end:4}],analysis:{key:'x',duration:4,rate:1,energy:[.5,.8,.4,.3],beats:[0,1,2,3]}});const a=recording(),b=recording();F.draw(a,p,1.25);F.draw(b,p,2.5);b.calls.length=0;F.draw(b,p,1.25);assert.deepEqual(a.calls,b.calls,type);const c=recording();F.draw(c,p,1.25,'back',true);assert.deepEqual(a.calls,c.calls,type);}});
test('bounded flash caps and hostile input normalization protect rendering workload',()=>{const s=F.normalize({enabled:true,manual:true,manualEffects:Array.from({length:100},(_,i)=>({id:'fx-'+i,type:'Light Flash',opacity:9,scale:10,params:{brightness:5,range:8,count:100000}}))});assert.equal(F.active(s,.3,'back').length,20);const ctx=recording();F.draw(ctx,{studio:{instrumentalFx:s}},.3);const flashes=ctx.calls.filter(c=>c[0]==='arc');assert(flashes.every(c=>c[3]<=360*.22/10));assert.equal(s.manualEffects[0].params.count,160);});
test('dense irregular imported beats cannot bypass one-second flash spacing',()=>{const s=F.normalize({analysis:{key:'dense',duration:5,rate:1,beats:Array.from({length:500},(_,i)=>i*.01),bpm:60}}),e=F.effect({id:'flash',type:'Light Flash',start:0,end:5,params:{duration:.2}});const events=[...new Set(Array.from({length:500},(_,i)=>F.flashEvent(s,e,i*.01)))];for(let i=1;i<events.length;i++)assert(events[i]-events[i-1]>=1);assert(events.length<=5);});
test('flash fallback keeps nonzero-start periodic events despite decimal rounding',()=>{const s=F.normalize(),e=F.effect({id:'flash',type:'Light Flash',start:10,end:20});assert(Math.abs(F.flashEvent(s,e,11.3)-11.2)<1e-9);});
