const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context=vm.createContext({J:{defaultProject:()=>({version:1}),upgradeLayerProject:()=>{},plan:()=>({}),layerText:(a,b)=>b},DOMException,AbortController,console});
for(const f of ['11za_va_schema.js','11zb_va_metrics.js','11zc_va_safe.js','11zd_va_frames.js'])vm.runInContext(fs.readFileSync('src/'+f,'utf8'),context);const V=context.J.VideoAnalysis,json=o=>JSON.parse(JSON.stringify(o));
function pixels(w,h,fn){const a=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const c=fn(x,y),i=(y*w+x)*4;a.set([...c,255],i);}return a;}
const solid=(r,g,b)=>pixels(96,64,()=>[r,g,b]);
test('regional luminance, contrast, extrema and edge density use actual pixels',()=>{const a=V.metrics(pixels(96,64,(x,y)=>x<48?[20,20,20]:[240,240,240]),96,64,null,0,false);assert(a.brightness.light[0]<.1);assert(a.brightness.light[7]>.9);assert(a.brightness.contrast>.4);assert(Math.abs(a.brightness.rgb[0]-.5098)<.001);});
test('scene changes use chroma/features while exposure changes are flash candidates',()=>{const dark=V.metrics(solid(20,20,20),96,64,null,0,false);const flash=V.metrics(solid(230,230,230),96,64,dark.state,.5,true);assert.equal(flash.change,'flash');assert.equal(flash.motion.strength,0);const red=V.metrics(solid(255,0,0),96,64,dark.state,.5,true);assert.equal(red.change,'cut');assert.equal(red.motion.strength,0);});
test('block matching reports rightward displacement per second and rejects flat-field confidence',()=>{const texture=(x,y)=>{if(x<0)return[0,0,0];const v=((x*374761393+y*668265263)^(x*y*127))>>>0;const c=(v^(v>>>13))&255;return[c,c,c]};const old=V.metrics(pixels(160,96,texture),160,96,null,0,true);const moved=V.metrics(pixels(160,96,(x,y)=>texture(x-3,y)),160,96,old.state,.5,true);assert(moved.motion.dx>0,JSON.stringify(moved.motion));assert(moved.motion.confidence>0);const flat=V.metrics(pixels(160,96,()=>[80,80,80]),160,96,null,0,true);const still=V.metrics(pixels(160,96,()=>[80,80,80]),160,96,flat.state,.5,true);assert.equal(still.motion.confidence,0);});
function fixture(faceSide='left') {const hash='a'.repeat(64),grid=Array.from({length:144},(_,i)=>faceSide==='left'?(i%16<7?1:0):(i%16>8?1:0));const sample=t=>({t,videoTime:t,faces:[{x:faceSide==='left'?.03:.65,y:.15,w:.3,h:.65,score:.95,trackId:'face-1',estimated:false}],person:{grid,occupancy:.4,confidence:.9,box:null},visionSample:true,brightness:{mean:.05,min:0,max:.1,contrast:.02,rgb:[.05,.05,.05],light:Array(48).fill(.05),complexity:Array(48).fill(0)},motion:{dx:0,dy:0,strength:0,confidence:1,regions:Array(48).fill(0)},change:null,changeScore:0});return{format:'synthia-video-analysis',schemaVersion:1,source:{name:'a.mp4',kind:'video',size:1000,width:640,height:360,duration:2,hash,hashMode:'full'},range:{start:0,end:2},options:V.options({}),samples:[sample(0),sample(1),sample(2)],scenes:[{id:'scene-0',start:0,end:2}],models:{face:'fixture',person:'fixture',runtime:'fixture'},warnings:[],safeZones:{}};}
test('safe zones avoid a left/right face and silhouette over the whole subtitle interval',()=>{for(const side of ['left','right']){const r=fixture(side),c=V.evaluateSafe(r,[],{start:0,end:2},{w:.24,h:.16},1);assert.equal(c.length,3);assert(c[0].safe);assert(c[0].faceRisk<.02);assert.equal(c[0].personRisk,0);assert(side==='left'?c[0].rect.x>.4:c[0].rect.x<.4);}});
test('manual protection, incomplete detection and sparse coverage never assert safe placement',()=>{const r=fixture(),all={x:0,y:0,w:1,h:1,start:0,end:2,sourceHash:r.source.hash};assert(V.evaluateSafe(r,[all],{start:0,end:2},{w:.2,h:.1},1).every(c=>!c.safe&&c.score<=15));r.models.person='';assert(V.evaluateSafe(r,[],{start:0,end:2},{w:.2,h:.1},1).every(c=>!c.safe));r.models.person='fixture';r.samples=[r.samples[0],{...r.samples[2],t:10}];r.range.end=10;assert(V.evaluateSafe(r,[],{start:0,end:2},{w:.2,h:.1},1).every(c=>!c.safe));});
test('moving faces protect both sides and too-large lyric envelopes have no candidate',()=>{const r=fixture();r.samples[1].faces=[{...r.samples[1].faces[0],x:.6}];const candidates=V.evaluateSafe(r,[],{start:0,end:2},{w:.3,h:.3},1);assert(candidates.every(c=>!c.safe));assert.equal(V.evaluateSafe(r,[],{start:0,end:2},{w:.98,h:.3},1).length,0);});
test('result import validates timestamps and source fingerprint, retaining project compatibility',()=>{const r=fixture(),clean=V.validateResult(json(r));assert.equal(clean.mapping.holdLastFrame,true);assert.equal(V.sameSource(clean.source,{...clean.source,name:'renamed.mp4'}),true);assert.equal(V.sameSource(clean.source,{...clean.source,hash:'b'.repeat(64)}),false);r.samples[1].t=-1;assert.throws(()=>V.validateResult(r),/timestamps/);const p=context.J.defaultProject();context.J.upgradeLayerProject(p,{videoAnalysis:{result:r}});assert.equal(p.version,1);assert.equal(p.videoAnalysis.result,null);assert(p.videoAnalysis.loadWarning);});
test('analysis time scheduling respects range/cap and letterbox transforms are invertible',()=>{assert.deepEqual(json(V.times(1,10,4,4)),[1,4,7,10]);const fit=V.fit({width:1920,height:1080},1080,1920),rect={x:.1,y:.2,w:.3,h:.4},p=V.toProject(rect,fit),back=V.toVideo(p,fit);for(const k in rect)assert(Math.abs(back[k]-rect[k])<1e-10);assert(fit.h<1);assert.throws(()=>V.times(4,2,2,10),/range/);});
test('held final video frame and static images cover later subtitles; partial video ranges do not',()=>{const r=fixture();assert(V.evaluateSafe(r,[],{start:3,end:5},{w:.2,h:.1},1)[0].safe);r.range.end=1;r.samples=r.samples.slice(0,2);assert.equal(V.evaluateSafe(r,[],{start:3,end:5},{w:.2,h:.1},1).length,0);r.source.kind='image';r.source.duration=null;r.samples=[r.samples[0]];assert(V.evaluateSafe(r,[],{start:30,end:35},{w:.2,h:.1},1)[0].safe);});
test('JSON roundtrip retains recommendation reasons and protected-region collisions',()=>{const r=fixture();r.safeZones['line-0']={text:'sample',start:0,end:2,candidates:V.evaluateSafe(r,[{x:0,y:0,w:1,h:1,start:0,end:2,sourceHash:r.source.hash}],{start:0,end:2},{w:.2,h:.1},1)};const saved=V.validateResult(json(r));assert.equal(saved.safeZones['line-0'].candidates[0].manualRisk,1);assert.equal(saved.safeZones['line-0'].candidates[0].recommendedColor,'#ffffff');assert.equal(saved.safeZones['line-0'].candidates[0].covered,true);});
