/* Opt-in FX editor. Existing chronological undo and both autosave paths are reused. */
(() => {
'use strict';
function boot(){
  const F=J.InstrumentalFX,el=J.studioElement,tr=J.layerText,root=J.studioSection('instrumentalFx','間奏演出 / Instrumental FX','Instrumental FX'),fields={},regionFields={},settings={},paramFields={};
  let selectedRegion='',selectedEffect='',pending=null,proposalKey='',job=null,drag=null,previewDrag=null,direct=false;
  const state=()=>J.ui.project.studio.instrumentalFx,all=()=>[...state().autoEffects,...state().manualEffects],current=()=>all().find(e=>e.id===selectedEffect),region=()=>state().regions.find(r=>r.id===selectedRegion);
  const busy=()=>!!J.ui.exporting||J.layerSession.busy||!!job;
  const mutate=fn=>{if(busy())return;J.uiApi.pushEdit();fn();J.studioChanged();};
  const status=el('p',null,'ifxStatus');status.setAttribute('role','status');status.setAttribute('aria-live','polite');let notice='';
  const actions=el('div');actions.className='ifx-actions';
  const button=(id,ja,en,fn,parent=root)=>{const b=J.studioButton('ifx'+id,ja,en,fn);parent.append(b);return b;};
  const grid=parent=>{const g=el('div');g.className='ifx-fields';parent.append(g);return g;};
  function input(parent,id,ja,en,type='number',options=null){
    const label=el('label',tr(ja,en)),i=el(options?'select':'input',null,'ifx'+id);if(options){for(const value of options){const o=el('option',value);o.value=value;i.append(o);}}else{i.type=type;if(type==='number'){i.min='0';i.max='86400';i.step='.01';}}
    i.setAttribute('aria-label',tr(ja,en));label.append(i);parent.append(label);return i;
  }
  function check(parent,id,ja,en,key){const i=input(parent,id,ja,en,'checkbox');settings[key]=i;i.addEventListener('change',()=>{if(key==='enabled'&&job){job.ac.abort();J.uiApi.pushEdit();state()[key]=i.checked;J.studioChanged();}else mutate(()=>{state()[key]=i.checked;});});return i;}
  const switches=grid(root);
  for(const [key,ja,en] of [['enabled','間奏演出 ON / OFF','Enable Instrumental FX'],['auto','自動エフェクト ON / OFF','Auto FX'],['manual','手動エフェクト ON / OFF','Manual FX'],['preview','プレビュー表示','Show in preview']])check(switches,key,ja,en,key);
  root.append(status,el('p',tr('歌詞タイミングの空白を検出します。歌声の有無は判定しません。OFFでも編集データを保持します。','Detect gaps in lyric timings; this does not identify vocal absence. OFF retains all editing data.')));
  const controls=el('fieldset',null,'ifxControls');root.append(controls);const config=grid(controls);
  for(const [key,ja,en] of [['strength','自動生成強度（%）','Generation strength (%)'],['minGap','最小区間（秒）','Minimum gap (s)'],['boundary','字幕境界の余白（秒）','Lyric boundary padding (s)'],['seed','生成シード','Generation seed']]){
    const i=input(config,key,ja,en);settings[key]=i;i.max=key==='strength'?'100':key==='seed'?'4294967295':key==='boundary'?'1':'120';i.min=key==='minGap'?'.1':'0';i.step=key==='seed'?'1':'.1';i.addEventListener('change',()=>{if(!i.checkValidity()||!Number.isFinite(i.valueAsNumber)){sync();return;}mutate(()=>state()[key]=i.valueAsNumber);});
  }
  for(const [key,ja,en,options] of [['style','スタイル','Style',F.styles],['pattern','生成パターン','Pattern',F.patterns],['quality','描画品質','Render quality',['low','standard','high']]]){const i=input(config,key,ja,en,'text',options);settings[key]=i;i.addEventListener('change',()=>mutate(()=>state()[key]=i.value));}
  for(const [key,ja,en] of [['beat','自動ビート連動','Auto beat response'],['avoidPeople','人物・顔を避ける（解析済み時のみ）','Avoid faces / people (matching analysis only)'],['safeFlash','発光・フラッシュ制限','Limit flashes'],['snap','FXクリップをビートにスナップ','Snap FX clips to beats']])check(config,key,ja,en,key);
  const sectionPanel=el('details');sectionPanel.open=true;sectionPanel.append(el('summary',tr('前奏・間奏・アウトロの区間','Intro / interlude / outro sections')));controls.append(sectionPanel);
  const duration=input(sectionPanel,'Duration','検出用の楽曲全長（秒、無音源時は手入力）','Detection duration (s; enter manually without audio)');duration.value='30';duration.min='.01';
  const length=()=>J.ui.audio?.duration||state().duration;
  const detect=()=>{const s=state(),cues=F.timelineInput(J.ui.project,J.ui.plan);pending=F.detect(cues,length(),s.minGap,s.boundary);proposalKey=F.detectionKey(cues,length(),s.minGap,s.boundary);syncProposal();};
  const proposal=el('div',null,'ifxDetectionProposal');proposal.setAttribute('aria-live','polite');
  function syncProposal(){proposal.replaceChildren();if(!pending)return;const merged=F.reconcile(state().regions,pending);proposal.append(el('p',tr('再検出候補：','Detected candidates: ')+pending.length+tr('件。手動調整と重なる候補：','; overlapping manual adjustments: ')+merged.conflicts.length));for(const r of pending)proposal.append(el('p',`${r.type}: ${r.start.toFixed(3)} – ${r.end.toFixed(3)} s`));}
  button('Detect','区間を検出・確認','Detect / review sections',detect,sectionPanel);
  button('AcceptDetection','候補を採用（手動調整を保持）','Accept (retain adjusted sections)',()=>{if(!pending)return;mutate(()=>{state().regions=F.reconcile(state().regions,pending).regions;state().detectionKey=proposalKey;pending=null;});syncProposal();},sectionPanel);
  button('ReplaceDetection','全区間を候補へ置換','Replace all sections with candidates',()=>{if(!pending||!confirm(tr('手動調整した区間も置換します。FXと字幕時刻は保持します。','Replace adjusted sections too? FX and lyric timings are retained.')))return;mutate(()=>{state().regions=pending;state().detectionKey=proposalKey;pending=null;});syncProposal();},sectionPanel);
  button('DiscardDetection','候補を閉じる','Dismiss candidates',()=>{pending=null;syncProposal();},sectionPanel);sectionPanel.append(proposal);
  const regionList=input(sectionPanel,'Region','対象区間','Target section','text',[]);regionList.addEventListener('change',()=>{selectedRegion=regionList.value;sync();});
  const rg=grid(sectionPanel);
  for(const [key,ja,en,type,options] of [['name','区間名','Section name','text'],['start','開始（秒）','Start (s)','number'],['end','終了（秒）','End (s)','number'],['type','区間種別','Section type','text',['Intro','Interlude','Outro','Custom']],['auto','自動生成対象','Generate Auto FX','checkbox']]){
    const i=input(rg,'Region-'+key,ja,en,type,options);regionFields[key]=i;i.addEventListener('change',()=>{const r=region();if(!r)return;const next={...r,[key]:type==='checkbox'?i.checked:type==='number'?i.valueAsNumber:i.value,edited:true};if(!Number.isFinite(next.start)||!Number.isFinite(next.end)||next.start<0||next.end<=next.start||next.end>86400){notice=tr('終了は開始より後、0〜86400秒で入力してください。','Enter valid times: end after start, within 0–86400 s.');sync();return;}mutate(()=>state().regions=F.regions(state().regions.map(x=>x.id===r.id?next:x)));});
  }
  button('AddRegion','区間を追加','Add section',()=>mutate(()=>{const start=Math.min(86397,J.ui.t),r={id:F.id(),name:'Custom',type:'Custom',start,end:start+3,auto:true,edited:true};state().regions.push(r);selectedRegion=r.id;}),sectionPanel);
  button('DeleteRegion','区間を削除','Delete section',()=>mutate(()=>{state().regions=state().regions.filter(r=>r.id!==selectedRegion);selectedRegion='';}),sectionPanel);
  button('SplitRegion','再生位置で分割','Split at playhead',()=>{const r=region();if(!r)return;const t=J.ui.t;if(t<=r.start||t>=r.end)throw new Error(tr('区間内にシークしてから分割してください。','Seek inside the section before splitting.'));mutate(()=>{state().regions=state().regions.flatMap(x=>x.id===r.id?[{...x,end:t,edited:true},{...x,id:F.id(),start:t,name:x.name+' 2',edited:true}]:[x]);});},sectionPanel);
  button('MergeRegion','次の区間と結合','Merge with next section',()=>{const rows=[...state().regions].sort((a,b)=>a.start-b.start),i=rows.findIndex(r=>r.id===selectedRegion);if(i<0||!rows[i+1])return;mutate(()=>{const a=rows[i],b=rows[i+1];state().regions=state().regions.filter(r=>r.id!==b.id).map(r=>r.id===a.id?{...r,end:Math.max(a.end,b.end),type:'Custom',edited:true}:r);});},sectionPanel);
  button('SeekRegion','区間へシーク','Seek to section',()=>{if(region())J.uiApi.seek(region().start);},sectionPanel);
  controls.append(actions);
  async function generate(scope){
    if(busy())return;const project=J.ui.project,epoch=J.projectSessionEpoch,audio=J.ui.audio,key=F.audioKey(audio),before=JSON.stringify(state()),ac=new AbortController();job={ac,project,epoch,key};notice=tr('解析・生成中…','Analyzing / generating…');sync();
    try{
      if(scope==='effect'&&(!current()||current().source!=='auto'||current().locked))throw new Error(tr('ロックされていない自動FXを選択してください。','Select an unlocked Auto FX.'));
      const snapshot=F.normalize(copyState()),target=current()&&{...current()};
      const analysis=audio?.buffer?(snapshot.analysis?.key===key?snapshot.analysis:await F.compactAnalysis(audio,ac.signal)):snapshot.analysis;
      const regions=snapshot.regions.length?snapshot.regions:F.detect(F.timelineInput(project,J.ui.plan),length(),snapshot.minGap,snapshot.boundary);
      const subset=scope==='all'?regions:scope==='region'?regions.filter(r=>r.id===selectedRegion):[{id:target.regionId||target.id,start:target.start,end:target.end,auto:true}];
      if(!subset.length)throw new Error(tr('対象区間がありません。区間を追加・選択してください。','No target section. Add or select a section.'));
      let result=await F.generate(snapshot,subset,analysis,project,J.videoAnalysisUI,ac.signal);
      if(ac.signal.aborted||project!==J.ui.project||epoch!==J.projectSessionEpoch||key!==F.audioKey(J.ui.audio)||before!==JSON.stringify(state()))return;
      const s=state();let next;
      if(scope==='effect'){if(result[0])result=[F.effect({...result[0],id:target.id,start:target.start,end:target.end,regionId:target.regionId},'auto')];next=s.autoEffects.flatMap(e=>e.id===target.id?result.slice(0,1):[e]);}
      else{const ids=new Set(subset.map(r=>r.id)),lockedIds=new Set(s.autoEffects.filter(e=>e.locked).map(e=>e.id));next=[...s.autoEffects.filter(e=>e.locked||scope==='region'&&!ids.has(e.regionId)),...result.filter(e=>!lockedIds.has(e.id))];}
      if(next.length>512)throw new Error(tr('保持するFXを含めて512件を超えます。区間を短くしてください。','The result plus retained FX exceeds 512. Use shorter sections.'));
      J.uiApi.pushEdit();s.beforeGeneration=s.autoEffects.map(e=>({...e,params:{...e.params}}));s.analysis=analysis;s.regions=regions;s.autoEffects=next;
      notice=tr('生成完了：','Generated: ')+result.length+tr('件。AutoをONにして確認してください。',' FX. Enable Auto to review.');J.studioChanged();
    }catch(e){notice=e.name==='AbortError'?tr('中止しました。編集結果は保持しています。','Cancelled; edits retained.'):e.message;}finally{if(job?.ac===ac)job=null;sync();}
  }
  const copyState=()=>JSON.parse(JSON.stringify(state()));
  document.getElementById('audioFile').addEventListener('change',()=>job?.ac.abort(),true);
  const loadAudio=J.uiApi.loadAudioFile;J.uiApi.loadAudioFile=(...args)=>{job?.ac.abort();return loadAudio(...args);};
  button('Generate','全区間を生成','Generate all sections',()=>generate('all'),actions);
  button('RegenerateRegion','選択区間を再生成','Regenerate selected section',()=>generate('region'),actions);
  button('RegenerateEffect','選択FXを再生成','Regenerate selected FX',()=>generate('effect'),actions);
  const cancel=button('Cancel','解析・生成を中止','Cancel analysis / generation',()=>{job?.ac.abort();},actions);
  button('ResetAuto','自動演出をリセット','Reset Auto FX',()=>mutate(()=>{state().beforeGeneration=state().autoEffects;state().autoEffects=state().autoEffects.filter(e=>e.locked);}),actions);
  button('RestoreGeneration','生成前へ戻す','Restore before generation',()=>{if(state().beforeGeneration)mutate(()=>{state().autoEffects=state().beforeGeneration;state().beforeGeneration=null;});},actions);
  const editor=el('details');editor.open=true;editor.append(el('summary',tr('エフェクト追加・個別編集','Add / edit individual FX')));controls.append(editor);
  const kind=input(editor,'Type','追加するエフェクト','Effect to add','text',F.types);
  button('AddEffect','手動エフェクト追加','Add Manual FX',()=>mutate(()=>{if(state().manualEffects.length>=512)throw new Error('Manual FX limit: 512');const r=region(),start=r?.start??Math.min(86397,J.ui.t),e=F.effect({type:kind.value,start,end:r?.end??start+3,regionId:r?.id,seed:state().seed});state().manualEffects.push(e);selectedEffect=e.id;}),editor);
  const effectList=input(editor,'Effect','対象エフェクト','Target FX','text',[]);effectList.addEventListener('change',()=>{selectedEffect=effectList.value;sync();J.ui.need=true;});
  const eg=grid(editor);
  const common=[['name','名前','Name','text'],['start','開始（秒）','Start (s)','number'],['end','終了（秒）','End (s)','number'],['duration','表示時間（秒）','Duration (s)','number'],['x','X（%）','X (%)','number'],['y','Y（%）','Y (%)','number'],['scale','拡大率（%）','Scale (%)','number'],['rotation','回転（°）','Rotation (°)','number'],['opacity','不透明度（%）','Opacity (%)','number'],['color','カラー','Color','color'],['blend','ブレンド','Blend','text',J.STUDIO_BLENDS],['speed','演出速度','Speed','number'],['intensity','演出強度（%）','Intensity (%)','number'],['beat','ビート連動','Beat response','checkbox'],['plane','歌詞との重なり','Relative to lyrics','text',['back','front']],['visible','個別表示','Visible','checkbox'],['locked','個別ロック','Locked','checkbox']];
  const percents=['x','y','scale','opacity','intensity'];
  for(const [key,ja,en,type,options] of common){const i=input(eg,'Effect-'+key,ja,en,type,options);fields[key]=i;if(['x','y','rotation'].includes(key))i.min=key==='rotation'?'-360':'-200';if(key==='scale'){i.min='5';i.max='1000';}if(['opacity','intensity'].includes(key))i.max='100';
    i.addEventListener('change',()=>{const e=current();if(!e)return;let value=type==='checkbox'?i.checked:type==='number'?i.valueAsNumber:i.value;if(type==='number'&&(!Number.isFinite(value)||!i.checkValidity())){sync();return;}if(percents.includes(key))value/=100;const patch=key==='duration'?{end:e.start+value}:{[key]:value};const next={...e,...patch};if(next.end<=next.start||next.end>86400){notice=tr('終了は開始より後にしてください。','End must follow start.');sync();return;}mutate(()=>F.updateEffect(state(),e.id,patch));});}
  const specific=el('details');specific.append(el('summary',tr('エフェクト固有の設定','Type-specific settings')));editor.append(specific);const pg=grid(specific);
  const paramLabels={count:['粒子・図形・軌跡の数','Count'],velocity:['速度','Velocity'],size:['サイズ（画面短辺比）','Size (fraction of short edge)'],lifetime:['粒子の寿命（秒）','Particle lifetime (s)'],direction:['移動・拡散方向（°）','Direction (degrees)'],spread:['拡散角度（°）','Spread (degrees)'],beatResponse:['ビート反応強度','Beat response'],brightness:['明るさ','Brightness'],duration:['発光・アクセント時間（秒）','Flash / accent duration (s)'],fade:['フェード（秒）','Fade (s)'],range:['演出範囲（短辺比）','Range (short edge fraction)'],sensitivity:['音量反応感度','Audio sensitivity'],lineWidth:['線幅（短辺比）','Line width'],rotationSpeed:['回転速度（°/秒）','Rotation speed (degrees/s)'],travel:['移動量','Travel'],zoom:['拡大縮小・脈動倍率','Zoom / pulse scale'],pulse:['パルス強度','Pulse strength'],length:['軌跡の長さ','Trail length'],glow:['発光強度','Glow'],shape:['図形タイプ','Shape'],accent:['アクセント種類','Accent type']};
  const typeParams={ 'Particle Burst':['count','velocity','size','lifetime','direction','spread','beatResponse'], 'Light Flash':['brightness','duration','fade','range','sensitivity'], 'Geometry Motion':['shape','count','size','lineWidth','rotationSpeed','direction','travel','zoom'], 'Audio Pulse':['pulse','zoom','sensitivity','fade','range'], 'Light Trails':['length','count','velocity','direction','glow','fade'], 'Transition Accent':['accent','duration','range','count','fade'] };
  for(const [key,[ja,en]] of Object.entries(paramLabels)){const options=key==='shape'?['circle','square','triangle','line']:key==='accent'?['flash','converge','gather','diffuse']:null,i=input(pg,'Param-'+key,ja,en,'number',options);paramFields[key]=i;if(F.paramSpecs[key]){const [,lo,hi]=F.paramSpecs[key];i.min=String(lo);i.max=String(hi);i.step=key==='count'?'1':'.001';}i.addEventListener('change',()=>{const e=current();if(!e)return;const value=options?i.value:i.valueAsNumber;if(!options&&(!Number.isFinite(value)||!i.checkValidity())){sync();return;}mutate(()=>F.updateEffect(state(),e.id,{params:{[key]:value}}));});}
  function deleteEffect(){const e=current();if(!e||e.locked)return;mutate(()=>{const key=e.source==='auto'?'autoEffects':'manualEffects';state()[key]=state()[key].filter(x=>x.id!==e.id);selectedEffect='';});}
  button('Duplicate','選択FXを複製','Duplicate selected FX',()=>{const e=current();if(!e)return;mutate(()=>{if(state().manualEffects.length>=512)throw new Error('Manual FX limit: 512');const next=F.effect({...e,id:F.id(),locked:false});state().manualEffects.push(next);selectedEffect=next.id;});},editor);
  button('Delete','選択FXを削除','Delete selected FX',deleteEffect,editor);
  for(const [suffix,ja,en,delta] of [['Down','描画順を下へ','Lower in track',-1],['Up','描画順を上へ','Raise in track',1]])button(suffix,ja,en,()=>{const e=current();if(!e||e.locked)return;const key=e.source==='auto'?'autoEffects':'manualEffects',rows=state()[key],i=rows.findIndex(x=>x.id===e.id),next=i+delta;if(next<0||next>=rows.length)return;mutate(()=>[rows[i],rows[next]]=[rows[next],rows[i]]);},editor);
  button('Convert','選択Auto FXを手動へ変換','Convert selected Auto FX to Manual',()=>{const e=current();if(!e||e.source!=='auto'||e.locked)return;mutate(()=>{if(state().manualEffects.length>=512)throw new Error('Manual FX limit: 512');const next=F.effect({...e,id:F.id()});state().manualEffects.push(next);state().autoEffects=state().autoEffects.filter(x=>x.id!==e.id);selectedEffect=next.id;});},editor);
  button('SeekEffect','選択FXへシーク','Seek to selected FX',()=>{if(current())J.uiApi.seek(current().start+Math.min(.5,(current().end-current().start)/2));},editor);
  const directInput=input(editor,'Direct','プレビューでFXを直接編集','Edit FX directly in preview','checkbox');
  const characterMode=document.getElementById('studioCharacterMode'),fxOption=el('option','Instrumental FX');fxOption.value='instrumental';characterMode.append(fxOption);
  directInput.addEventListener('change',()=>{direct=directInput.checked;if(direct){characterMode.value='instrumental';characterMode.dispatchEvent(new Event('change'));}drawOverlay();});
  characterMode.addEventListener('change',()=>{if(characterMode.value!=='instrumental'){direct=false;directInput.checked=false;drawOverlay();}});
  editor.append(el('p',tr('直接編集時はFX中心をクリックして移動。四隅で拡大、上の丸で回転。個別選択・ロック・Undoに対応します。','Direct editing: click an FX center and drag to move; corners scale, top circle rotates. Selection, locks and Undo are per object.')));
  const presetPanel=el('details');presetPanel.append(el('summary',tr('FXプリセット','FX presets')));controls.append(presetPanel);
  const presetName=input(presetPanel,'PresetName','プリセット名','Preset name','text'),presetList=input(presetPanel,'Preset','プリセット','Preset','text',[]);let selectedPreset='';presetList.addEventListener('change',()=>{selectedPreset=presetList.value;presetName.value=state().presets.find(p=>p.id===selectedPreset)?.name||'';});
  button('SavePreset','選択FXをプリセット保存','Save selected FX as preset',()=>{if(!current())return;mutate(()=>{if(state().presets.length>=100)throw new Error('Preset limit: 100');const p={id:F.id(),name:presetName.value||current().name,effect:F.effect(current())};state().presets.push(p);selectedPreset=p.id;});},presetPanel);
  button('ApplyPreset','プリセット適用','Apply preset',()=>{const e=current(),p=state().presets.find(p=>p.id===selectedPreset);if(!e||!p)return;mutate(()=>{const {id,source,start,end,regionId,locked,seed,...style}=p.effect;F.updateEffect(state(),e.id,{...style,presetId:p.id});});},presetPanel);
  button('RenamePreset','プリセット名変更','Rename preset',()=>mutate(()=>{const p=state().presets.find(p=>p.id===selectedPreset);if(p)p.name=(presetName.value||p.name).slice(0,100);}),presetPanel);
  button('DeletePreset','プリセット削除','Delete preset',()=>mutate(()=>state().presets=state().presets.filter(p=>p.id!==selectedPreset)),presetPanel);
  button('DuplicatePreset','プリセット複製','Duplicate preset',()=>mutate(()=>{const p=state().presets.find(p=>p.id===selectedPreset);if(p&&state().presets.length<100){const q=JSON.parse(JSON.stringify(p));q.id=F.id();q.name+=' copy';state().presets.push(q);selectedPreset=q.id;}}),presetPanel);
  const track=el('canvas',null,'ifxTracks');track.width=720;track.height=90;track.style.width='100%';track.style.touchAction='none';track.setAttribute('aria-label',tr('間奏FXタイムライン（数値入力でも編集可能）','Instrumental FX timeline (numeric editing also available)'));
  const trackPanel=el('div',null,'ifxTrackPanel');trackPanel.append(el('h3','Instrumental Auto FX / Manual FX'),track,el('p',tr('クリップをドラッグで移動、左右端で長さ変更。SRTの時刻は変更しません。','Drag a clip to move; drag either edge to resize. SRT timings stay unchanged.')));document.getElementById('studio-timeline').append(trackPanel);
  const span=()=>Math.max(1,length(),...all().map(e=>e.end)),point=e=>{const r=track.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*90/r.height};};
  function drawTracks(){trackPanel.hidden=!state().enabled;const ctx=track.getContext('2d'),dur=span();ctx.clearRect(0,0,720,90);ctx.font='14px sans-serif';for(const [row,key,label,col] of [[0,'autoEffects','Auto FX','#547fb8'],[1,'manualEffects','Manual FX','#98754e']]){ctx.fillStyle='#242936';ctx.fillRect(105,12+row*34,610,28);ctx.fillStyle='#ddd';ctx.fillText(label,4,32+row*34);for(const e of state()[key]){const x=105+e.start/dur*610,w=Math.max(4,(e.end-e.start)/dur*610);ctx.globalAlpha=e.visible?1:.4;ctx.fillStyle=e.id===selectedEffect?'#79d9ae':col;ctx.fillRect(x,14+row*34,w,24);ctx.globalAlpha=1;ctx.save();ctx.beginPath();ctx.rect(x,14+row*34,w,24);ctx.clip();ctx.fillStyle='#fff';ctx.fillText((e.locked?'🔒 ':'')+e.name,x+3,31+row*34);ctx.restore();}}ctx.fillStyle='#e4bb72';ctx.fillRect(105+J.ui.t/dur*610,10,1,65);}
  track.addEventListener('pointerdown',e=>{if(e.button!==0||busy()||!state().enabled)return;const p=point(e),dur=span(),row=p.y>=46?1:0,time=(p.x-105)/610*dur,list=state()[row?'manualEffects':'autoEffects'],hits=list.filter(x=>time>=x.start&&time<=x.end),fx=hits.find(x=>x.id===selectedEffect)||hits.at(-1);if(!fx){J.uiApi.seek(Math.max(0,time));return;}selectedEffect=fx.id;sync();if(fx.locked)return;J.uiApi.pause();drag={effect:{...fx},point:p,time,dur,mode:Math.abs(p.x-(105+fx.start/dur*610))<9?'start':Math.abs(p.x-(105+fx.end/dur*610))<9?'end':'move',changed:false};track.setPointerCapture(e.pointerId);e.preventDefault();});
  track.addEventListener('pointermove',e=>{if(!drag||busy())return;const delta=(point(e).x-drag.point.x)/610*drag.dur,fx=drag.effect;let start=fx.start,end=fx.end;if(drag.mode==='move'){start=F.snapTime(Math.max(0,fx.start+delta),state().analysis,state().snap);end=start+fx.end-fx.start;}else if(drag.mode==='start')start=Math.min(end-.01,F.snapTime(Math.max(0,fx.start+delta),state().analysis,state().snap));else end=Math.max(start+.01,F.snapTime(fx.end+delta,state().analysis,state().snap));if(end>86400)return;if(!drag.changed){J.uiApi.pushEdit();drag.changed=true;}F.updateEffect(state(),fx.id,{start,end});J.ui.need=true;drawTracks();updateEffectFields();});
  const endDrag=()=>{if(drag?.changed)J.studioChanged();drag=null;};for(const event of ['pointerup','pointercancel','lostpointercapture'])track.addEventListener(event,endDrag);
  const view=document.getElementById('view'),overlay=el('canvas',null,'ifxOverlay');overlay.className='ifx-overlay';document.getElementById('viewport').append(overlay);let handles=[];
  function drawOverlay(){const e=current();overlay.hidden=!direct||!state().enabled||!state().preview||J.ui.playing||J.ui.exporting||!e||!F.active(state(),J.ui.t,e.plane,true).some(x=>x.id===e.id);if(overlay.hidden){handles=[];return;}
    const r=view.getBoundingClientRect(),vp=document.getElementById('viewport').getBoundingClientRect();overlay.width=view.width;overlay.height=view.height;Object.assign(overlay.style,{left:r.left-vp.left+'px',top:r.top-vp.top+'px',width:r.width+'px',height:r.height+'px'});const c=overlay.getContext('2d'),k=view.width/r.width,x=e.x*view.width,y=e.y*view.height,rad=Math.max(20*k,Math.min(view.width,view.height)*e.params.range*e.scale),left=x-rad,top=y-rad;c.strokeStyle=e.locked?'#aeb7c7':'#79d9ae';c.fillStyle='#151b24';c.lineWidth=1.5*k;c.strokeRect(left,top,rad*2,rad*2);handles=[[left,top],[left+rad*2,top],[left+rad*2,top+rad*2],[left,top+rad*2]].map(([x,y])=>({x,y,mode:'scale'}));handles.push({x,y:top-24*k,mode:'rotate'});for(const h of handles){c.beginPath();c.arc(h.x,h.y,5*k,0,J.TAU);c.fill();c.stroke();}}
  const vpoint=e=>{const r=view.getBoundingClientRect();return{x:(e.clientX-r.left)*view.width/r.width,y:(e.clientY-r.top)*view.height/r.height};};
  view.addEventListener('pointerdown',e=>{if(!direct||e.button!==0||busy()||!state().enabled||J.ui.playing||J.ui.tap)return;const p=vpoint(e),r=view.getBoundingClientRect(),radius=12*view.width/r.width,handle=handles.find(h=>Math.hypot(h.x-p.x,h.y-p.y)<=radius);if(!handle){const hits=all().filter(x=>F.active(state(),J.ui.t,x.plane,true).some(a=>a.id===x.id)&&Math.hypot(x.x*view.width-p.x,x.y*view.height-p.y)<Math.max(25*view.width/r.width,Math.min(view.width,view.height)*x.params.range*x.scale));if(!hits.length)return;selectedEffect=(hits.find(x=>x.id===selectedEffect)||hits.at(-1)).id;sync();}const fx=current();if(!fx)return;e.preventDefault();e.stopImmediatePropagation();if(fx.locked)return;previewDrag={effect:{...fx},point:p,mode:handle?.mode||'move',changed:false};view.setPointerCapture(e.pointerId);},true);
  view.addEventListener('pointermove',e=>{if(!previewDrag||busy())return;e.preventDefault();e.stopImmediatePropagation();const d=previewDrag,p=vpoint(e),fx=d.effect,dx=p.x-d.point.x,dy=p.y-d.point.y;if(!d.changed&&Math.hypot(dx,dy)<1)return;if(!d.changed){J.uiApi.pushEdit();d.changed=true;}const patch={};if(d.mode==='move'){patch.x=fx.x+dx/view.width;patch.y=fx.y+dy/view.height;}else{const x=fx.x*view.width,y=fx.y*view.height;if(d.mode==='scale')patch.scale=fx.scale*Math.hypot(p.x-x,p.y-y)/Math.max(1,Math.hypot(d.point.x-x,d.point.y-y));else patch.rotation=fx.rotation+(Math.atan2(p.y-y,p.x-x)-Math.atan2(d.point.y-y,d.point.x-x))/J.DEG;}F.updateEffect(state(),fx.id,patch);J.ui.need=true;updateEffectFields();drawOverlay();},true);
  for(const event of ['pointerup','pointercancel','lostpointercapture'])view.addEventListener(event,()=>{if(previewDrag?.changed)J.studioChanged();previewDrag=null;});
  const preview=J.drawLayerPreview;J.drawLayerPreview=(ctx,plan,t,opt)=>{const r=preview(ctx,plan,t,opt);if(ctx.canvas.id==='view'){drawOverlay();drawTracks();}return r;};
  function updateEffectFields(){const e=current();for(const [key,i] of Object.entries(fields)){i.disabled=!e||e.locked&&key!=='locked'||busy();if(!e)continue;if(i.type==='checkbox')i.checked=e[key];else i.value=String(key==='duration'?e.end-e.start:percents.includes(key)?Math.round(e[key]*10000)/100:e[key]);}for(const [key,i] of Object.entries(paramFields)){i.parentElement.hidden=!e||!typeParams[e.type].includes(key);i.disabled=!e||e.locked||busy();if(e)i.value=String(e.params[key]);}}
  let lastProject=null,lastCueKey='';
  function sync(){const s=state();if(!s)return;
    if(job&&(job.project!==J.ui.project||job.epoch!==J.projectSessionEpoch||job.key!==F.audioKey(J.ui.audio)||!s.enabled)){job.ac.abort();}
    if(lastProject!==J.ui.project){lastProject=J.ui.project;pending=null;selectedEffect='';selectedRegion='';notice='';lastCueKey='';proposalKey='';syncProposal();}
    const key=F.detectionKey(F.timelineInput(J.ui.project,J.ui.plan),length(),s.minGap,s.boundary);
    if(lastCueKey&&key!==lastCueKey&&s.regions.length){detect();notice=tr('歌詞・全長が変わりました。再検出候補を確認してください。編集区間は保持しています。','Lyrics / duration changed. Review new candidates; edited sections are retained.');}lastCueKey=key;
    for(const [key,i] of Object.entries(settings)){if(i.type==='checkbox')i.checked=s[key];else i.value=String(s[key]);i.disabled=busy()&&key!=='enabled';}controls.disabled=!s.enabled||!!J.ui.exporting||J.layerSession.busy;
    cancel.disabled=!job;for(const b of actions.querySelectorAll('button'))if(b!==cancel)b.disabled=!!job;
    duration.value=String(length());duration.disabled=!!J.ui.audio;
    if(!s.regions.some(r=>r.id===selectedRegion))selectedRegion=s.regions[0]?.id||'';regionList.replaceChildren(...s.regions.map(r=>{const o=el('option',`${r.name}: ${r.start.toFixed(2)} – ${r.end.toFixed(2)} s`);o.value=r.id;return o;}));regionList.value=selectedRegion;
    for(const [key,i] of Object.entries(regionFields)){const r=region();i.disabled=!r||busy();if(r){if(i.type==='checkbox')i.checked=r[key];else i.value=String(r[key]);}}
    if(!all().some(e=>e.id===selectedEffect))selectedEffect=all()[0]?.id||'';effectList.replaceChildren(...all().map(e=>{const o=el('option',`${e.source==='auto'?'Auto':'Manual'}: ${e.name}${e.locked?' 🔒':''}`);o.value=e.id;return o;}));effectList.value=selectedEffect;
    presetList.replaceChildren(...s.presets.map(p=>{const o=el('option',p.name);o.value=p.id;return o;}));if(!s.presets.some(p=>p.id===selectedPreset))selectedPreset=s.presets[0]?.id||'';presetList.value=selectedPreset;
    const valid=!!J.videoAnalysisUI?.valid&&!!J.ui.project.videoAnalysis?.result;
    status.textContent=(s.enabled?tr('間奏演出ON','Instrumental FX ON'):tr('間奏演出OFF（データ保持）','Instrumental FX OFF (data retained)'))+' · '+tr('自動 ','Auto ')+s.autoEffects.length+' / '+tr('手動 ','Manual ')+s.manualEffects.length+'\n'+(s.avoidPeople?(valid?tr('一致する映像解析結果で配置候補を評価します。回避は推定です。','Matching video results are used for placement; avoidance is heuristic.'):tr('有効な映像解析なし：通常配置。人物回避は未適用。','No valid matching video analysis: normal placement; people avoidance unavailable.')):'')+'\n'+notice;
    updateEffectFields();drawTracks();drawOverlay();
    // FX tracks remain accessible when the additional-layer extension is OFF.
    if(!J.studioOn(J.ui.project,'timeline'))controls.append(trackPanel);else document.getElementById('studio-timeline').append(trackPanel);
  }
  duration.addEventListener('change',()=>{if(!duration.checkValidity()||!Number.isFinite(duration.valueAsNumber)){sync();return;}mutate(()=>state().duration=duration.valueAsNumber);detect();sync();});
  const guide=el('a',tr('間奏演出の操作ガイド','Instrumental FX guide'));guide.href=document.documentElement.lang==='en'?'../docs/INSTRUMENTAL_FX.en.html':'docs/INSTRUMENTAL_FX.html';guide.target='_blank';guide.rel='noopener';root.append(guide,el('p',tr('完成MP4・簡易動画に間奏FXを含みます。字幕フロント／マット・PNG連番は歌詞専用で、間奏FXを含みません。','Completed / simple MP4 includes Instrumental FX. Subtitle front / matte and PNG sequences remain lyric-only and exclude FX.')));
  const old=J.syncLayerUI;J.syncLayerUI=()=>{old();sync();};sync();J.syncLayerUI();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
